import { nanoid } from 'nanoid';
import type { CampDay } from '@/types';

export const SAMPLE_DAY_6: CampDay = {
  id: nanoid(),
  dayNumber: 6,
  title: 'Día 6 - PILONES',
  date: new Date().toISOString().split('T')[0],
  timeSlots: [
    {
      id: nanoid(),
      time: '07:50',
      title: 'Despertador',
      description: 'Acordar os acampados',
      notes: [],
      completed: false,
    },
    {
      id: nanoid(),
      time: '08:20',
      title: 'Desayuno',
      description: 'Pequeno-almoço',
      notes: [
        'Aron, Gil e Sergio ficam na instalação',
        'Ruta: Nuria abre a rota, monis de apoio: Paula, Ainara, Gloria, Luis, Lucia, Juanmar, Laura, Lau, Sere e Zoe',
        'Carla baja en coche a los lisiados antes para que los suban en furgo hasta el chorreo de la virgen y esperar al resto del grupo',
        'O piquenique desce no carro de Clara e tem de ser levado para a base, tem de ficar carregado no carro à noite',
        'Clara e Sere fazem o piquenique na base no piso de cima',
      ],
      assignees: ['Nuria', 'Paula', 'Ainara', 'Gloria', 'Luis', 'Lucia', 'Juanmar', 'Laura', 'Lau', 'Sere', 'Zoe'],
      completed: false,
    },
    {
      id: nanoid(),
      time: '08:45',
      title: 'Salida en bus',
      description: 'Saída em autocarro para Jerte',
      notes: [
        'COISAS A LEVAR:',
        'Garrafas de água 6/8 (Luis e Ainara)',
        'Jogos de mesa (Juanmar)',
        'Bolas (Paula)',
        'Distribuir aos miúdos no pequeno-almoço água, sumo e fruta, encarregam-se Aron e Sergio',
        'Mochila de primeiros socorros Laura e Gloria',
      ],
      assignees: ['Luis', 'Ainara', 'Juanmar', 'Paula', 'Aron', 'Sergio', 'Laura', 'Gloria'],
      completed: false,
    },
    {
      id: nanoid(),
      time: '09:30',
      title: 'Llegada a Jerte - Inicio Ruta',
      description: 'Chegada e início da rota de Pilones',
      notes: [
        'Briefing Pilones - Nuria',
        'Monitores cada 10/12 miúdos',
        'Descida de pilones em grupos pequenos (Luis, Paula, Laura, Ainara e Nuria) (37/40 miúdos) + Carla',
      ],
      assignees: ['Nuria', 'Luis', 'Paula', 'Laura', 'Ainara', 'Carla'],
      completed: false,
    },
    {
      id: nanoid(),
      time: '14:30',
      title: 'Piquenique',
      description: 'Aproximadamente - MÁXIMA COORDENAÇÃO com o grupo de Piquenique',
      notes: [
        'Subirão o piquenique até ao refúgio do Escribano',
        'Tem de ir recolher entre monitores e acampados',
        'Come-se ali e passa-se ali toda a jornada',
      ],
      assignees: ['Clara', 'Sere'],
      completed: false,
    },
    {
      id: nanoid(),
      time: '17:00',
      title: 'Recogida y bajada al merendero',
      description: 'Recolha e descida ao merendouro',
      notes: [],
      assignees: [],
      completed: false,
    },
    {
      id: nanoid(),
      time: '18:30',
      title: 'Vuelta al campamento',
      description: 'Regresso ao acampamento',
      notes: [],
      assignees: [],
      completed: false,
    },
    {
      id: nanoid(),
      time: '19:30',
      title: 'Duchas',
      description: 'Banho',
      notes: [],
      assignees: [],
      completed: false,
    },
    {
      id: nanoid(),
      time: '20:30',
      title: 'Cena',
      description: 'Jantar',
      notes: [],
      assignees: [],
      completed: false,
    },
    {
      id: nanoid(),
      time: '22:00',
      title: 'Velada',
      description: 'Histórias das estrelas / Relaxamento',
      notes: ['Cuentos de las estrellas / relajación'],
      assignees: [],
      completed: false,
    },
  ],
  createdAt: Date.now(),
  updatedAt: Date.now(),
};

export const initializeSampleData = (): CampDay[] => {
  return [SAMPLE_DAY_6];
};
